#!/usr/bin/env python

import sys

from lapchart_data import chartdata
from lapchart_gui import LapChartGUI
from data_file_io import load_file, save_data_file
from printing import save_ps

if __name__ == '__main__':
    if len(sys.argv) == 4 and sys.argv[1] == '-P':
        data = chartdata()
        load_file(data, sys.argv[2])
        save_ps(data, sys.argv[3])
        sys.exit(0)

    if len(sys.argv) >= 4 and sys.argv[1] == '-C':
        data = chartdata()
        load_file(data, sys.argv[2])
        for arg in sys.argv[4:]:
            (k,v) = arg.split('=', 1)
            data.props[k] = v
        save_data_file(data, sys.argv[3])
        sys.exit(0)

    gui = LapChartGUI(files=sys.argv[1:])
    gui.mainloop()
